export const UPDATE_STATE = "updatestate";


// Car //
export const CAR_START = 'CAR_START';
export const CAR_SUCCESS = 'CAR_SUCCESS';
export const CAR_ERROR = 'CAR_ERROR';
export const CAR_GET_ID_START = 'CAR_GET_ID_START';
export const CAR_GET_ID_SUCCESS = 'CAR_GET_ID_SUCCESS';
export const CAR_GET_ID_ERROR = 'CAR_GET_ID_ERROR';
export const CAR_POST_START = 'CAR_POST_START';
export const CAR_POST_SUCCESS = 'CAR_POST_SUCCESS';
export const CAR_POST_ERROR = 'CAR_POST_ERROR';
export const CAR_UPDATE_START = 'CAR_UPDATE_START';
export const CAR_UPDATE_SUCCESS = 'CAR_UPDATE_SUCCESS';
export const CAR_UPDATE_ERROR = 'CAR_UPDATE_ERROR';
export const CAR_DELETE_START = 'CAR_DELETE_START';
export const CAR_DELETE_SUCCESS = 'CAR_DELETE_SUCCESS';
export const CAR_DELETE_ERROR = 'CAR_DELETE_ERROR';

// Status //

export const SUCCESS_STATUS = 'SUCCESS_STATUS';
export const ERROR_STATUS = 'ERROR_STATUS';
export const CLEAR_STATUS = 'CLEAR_STATUS';

// Order //

export const ORDER_POST_START = 'ORDER_POST_START';
export const ORDER_POST_SUCCESS = 'ORDER_POST_SUCCESS';
export const ORDER_POST_ERROR = 'ORDER_POST_ERROR';
export const ORDER_GET_START = 'ORDER_GET_START';
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS';
export const ORDER_GET_ERROR = 'ORDER_GET_ERROR';
export const ORDER_UPDATE_START = 'ORDER_UPDATE_START';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_ERROR = 'ORDER_UPDATE_ERROR';
export const ORDER_DELETE_START = 'ORDER_DELETE_START';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_ERROR = 'ORDER_DELETE_ERROR';

// brand //

export const BRAND_GET_START = 'BRAND_GET_START';
export const BRAND_GET_SUCCESS = 'BRAND_GET_SUCCESS';
export const BRAND_GET_ERROR = 'BRAND_GET_ERROR';
export const BRAND_POST_START = 'BRAND_POST_START';
export const BRAND_POST_SUCCESS = 'BRAND_POST_SUCCESS';
export const BRAND_POST_ERROR = 'BRAND_POST_ERROR';
export const BRAND_UPDATE_START = 'BRAND_UPDATE_START';
export const BRAND_UPDATE_SUCCESS = 'BRAND_UPDATE_SUCCESS';
export const BRAND_UPDATE_ERROR = 'BRAND_UPDATE_ERROR';
export const BRAND_DELETE_START = 'BRAND_DELETE_START';
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS';
export const BRAND_DELETE_ERROR = 'BRAND_DELETE_ERROR';

// category //

export const CATEGORY_GET_START = 'CATEGORY_GET_START';
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';
export const CATEGORY_GET_ERROR = 'CATEGORY_GET_ERROR';
export const CATEGORY_POST_START = 'CATEGORY_POST_START';
export const CATEGORY_POST_SUCCESS = 'CATEGORY_POST_SUCCESS';
export const CATEGORY_POST_ERROR = 'CATEGORY_POST_ERROR';
export const CATEGORY_UPDATE_START = 'CATEGORY_UPDATE_START';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_ERROR = 'CATEGORY_UPDATE_ERROR';
export const CATEGORY_DELETE_START = 'CATEGORY_DELETE_START';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_ERROR = 'CATEGORY_DELETE_ERROR';
